trigger: none

pool:
    vmImage: ubuntu-latest
stages:
  - stage: Buildstage
    displayName: Buildstage
    jobs:
      - job: buildjob
        displayName: build job
        steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: CmdLine@2
          inputs:
           script: 'npm run build' 
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/build/'
            ArtifactName: 'todo-app'
            publishLocation: 'Container'