trigger: none

pool:
    vmImage: ubuntu-latest
stages:
  - stage: Buildstage
    displayName: Buildstage
    jobs:
      - job: buildjob
        displayName: build job
        steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: CmdLine@2
          inputs:
           script: 'npm run build' 
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/build/'
            ArtifactName: 'todo-app'
            publishLocation: 'Container'

  - stage: Deploystage
    displayName: Deploystage
    jobs:
      - job: Deploystage
        displayName: Deploy job
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'todo-app'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: CopyFilesOverSSH@0
          inputs:
            sshEndpoint: 'sshconnection'
            sourceFolder: '$(System.ArtifactsDirectory)/todo app'
            contents: '**'
            targetFolder: '/var/www/html/'
            readyTimeout: '20000'
        - task: SSH@0
          inputs:
            sshEndpoint: 'sshconnection'
            runOptions: 'commands'
            commands: 'sudo systemctl restart nginx'
            readyTimeout: '20000'